import {
  ShoppingCart,
  CreditCard,
  Home,
  Car,
  Utensils,
  Briefcase,
  HeartPulse,
  Plane,
  GraduationCap,
  DollarSign,
  Gift,
  Coffee,
  Smartphone,
  Wifi,
  Zap,
  Bus,
  Film,
  Music,
  Shirt,
  Baby,
  Wallet,
  Landmark,
  Wrench,
  Scissors,
  Bike,
  Dog,
  Cat,
  CircleDot,
  Gamepad2,
  Book,
  Dumbbell,
  Pill,
  Stethoscope,
  Droplet,
  Flame,
  Tv,
  Ticket,
  Tent,
  Umbrella,
  Hammer,
  Truck,
  Train,
  Tractor,
  Ship,
  ParkingMeterIcon as Parking,
  Newspaper,
  Lightbulb,
  Key,
  Flower2,
  Fish,
  Drumstick,
  Cigarette,
  Building,
  Brush,
  Banana,
  Armchair,
  Apple,
  AlarmClockIcon as Alarm,
  Trash2,
  Receipt,
  Percent,
  Package,
  Mailbox,
  Hourglass,
  Globe,
  Gem,
  Factory,
  Eye,
  Coins,
  Church,
  Cake,
  Bed,
  Bath,
  Backpack,
  Axe,
  Atom,
  Ambulance,
  Plug,
  Palette,
  Microscope,
  Laptop,
  Keyboard,
  Joystick,
  HardDrive,
  Headphones,
  Gauge,
  Cpu,
  Cog,
  Cloud,
  Clipboard,
  Bell,
  Banknote,
  Award,
  Aperture,
  Antenna,
} from "lucide-react"

// Map of icon names to their components
export const categoryIcons = {
  // Common icons
  ShoppingCart,
  CreditCard,
  Home,
  Car,
  Utensils,
  Briefcase,
  HeartPulse,
  Plane,
  GraduationCap,
  DollarSign,
  Gift,
  Coffee,
  Smartphone,
  Wifi,
  Zap,
  Bus,
  Film,
  Music,
  Shirt,
  Baby,
  Wallet,
  Landmark,
  Wrench,
  Scissors,
  CircleDot,

  // Transportation
  Bike,
  Truck,
  Train,
  Tractor,
  Ship,
  Parking,

  // Home & Living
  Lightbulb,
  Key,
  Flower2,
  Building,
  Brush,
  Armchair,
  Bed,
  Bath,
  Plug,

  // Food & Dining
  Fish,
  Drumstick,
  Banana,
  Apple,
  Cake,

  // Health & Wellness
  Pill,
  Stethoscope,
  Dumbbell,
  Cigarette,

  // Entertainment
  Gamepad2,
  Book,
  Tv,
  Ticket,
  Tent,
  Newspaper,
  Palette,
  Microscope,
  Laptop,
  Keyboard,
  Joystick,
  HardDrive,
  Headphones,

  // Utilities
  Droplet,
  Flame,
  Umbrella,
  Hammer,
  Trash2,
  Receipt,
  Package,
  Mailbox,
  Globe,

  // Animals
  Dog,
  Cat,

  // Finance
  Percent,
  Gem,
  Factory,
  Coins,
  Church,
  Banknote,
  Award,

  // Technology
  Gauge,
  Cpu,
  Cog,
  Cloud,
  Clipboard,
  Bell,
  Aperture,
  Antenna,

  // Time
  Hourglass,
  Alarm,

  // Other
  Eye,
  Axe,
  Atom,
  Ambulance,
  Backpack,
}

// Helper function to get an icon component by name
export function getIconByName(name: string) {
  return categoryIcons[name as keyof typeof categoryIcons] || CircleDot
}

// List of all available icon names
export const iconNames = Object.keys(categoryIcons)

// Common icons for categories - show these first
export const commonIcons = [
  "ShoppingCart",
  "CreditCard",
  "Home",
  "Car",
  "Utensils",
  "Briefcase",
  "HeartPulse",
  "Plane",
  "GraduationCap",
  "DollarSign",
  "Gift",
  "Coffee",
  "Smartphone",
  "Wifi",
  "Zap",
  "Bus",
  "Film",
  "Music",
  "Shirt",
  "Baby",
  "Wallet",
  "Landmark",
  "Wrench",
  "Scissors",
]

// Categorized icons for better organization
export const iconCategories = [
  {
    name: "Finance",
    icons: ["DollarSign", "CreditCard", "Wallet", "Landmark", "Coins", "Receipt", "Percent", "Banknote", "Award"],
  },
  {
    name: "Shopping",
    icons: ["ShoppingCart", "Shirt", "Gift", "Package", "Bag", "Gem"],
  },
  {
    name: "Home",
    icons: ["Home", "Bed", "Bath", "Armchair", "Lightbulb", "Flame", "Droplet", "Key", "Building", "Flower2"],
  },
  {
    name: "Transportation",
    icons: ["Car", "Plane", "Bus", "Train", "Bike", "Truck", "Ship", "Tractor", "Parking"],
  },
  {
    name: "Food & Dining",
    icons: ["Utensils", "Coffee", "Cake", "Apple", "Banana", "Fish", "Drumstick"],
  },
  {
    name: "Health",
    icons: ["HeartPulse", "Pill", "Stethoscope", "Dumbbell", "Ambulance"],
  },
  {
    name: "Education",
    icons: ["GraduationCap", "Book", "Microscope"],
  },
  {
    name: "Technology",
    icons: ["Smartphone", "Wifi", "Laptop", "Headphones", "Tv", "HardDrive", "Cpu", "Keyboard", "Joystick", "Plug"],
  },
  {
    name: "Entertainment",
    icons: ["Film", "Music", "Gamepad2", "Ticket", "Palette"],
  },
  {
    name: "Utilities",
    icons: ["Wrench", "Scissors", "Hammer", "Umbrella", "Trash2"],
  },
  {
    name: "Other",
    icons: ["Baby", "Dog", "Cat", "CircleDot", "Globe", "Cloud", "Eye", "Bell", "Newspaper", "Tent"],
  },
]

